In [1]:
import numpy as np

### Consider the below code to answer further questions:

In [14]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

type of list_ is list and type of array_list is ndarray

In [16]:
type(list_)

list

In [17]:
type(array_list)

numpy.ndarray

### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [19]:
for i in list_:
    print(type(i))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [20]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:


In [22]:
array_list = np.array(object = list_, dtype = int)


Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Answer: No change in data type of elements in list_, where as elements in array_list will change to int32

In [23]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [24]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


### Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [9]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [10]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
num_array.shape

(2, 3)

In [12]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])